// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkjZWF1naB4QD2q9QYBpaIgJIQhVuXeic',
    appId: '1:18656785307:web:6084779417b10edf18273e',
    messagingSenderId: '18656785307',
    projectId: 'mynotes-e163f',
    authDomain: 'mynotes-e163f.firebaseapp.com',
    storageBucket: 'mynotes-e163f.appspot.com',
    measurementId: 'G-4F1FPBQQVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgQIIFRApgQ6u_OPTDXmXp2ozF2H_usZI',
    appId: '1:18656785307:android:89a1c6ca86015db718273e',
    messagingSenderId: '18656785307',
    projectId: 'mynotes-e163f',
    storageBucket: 'mynotes-e163f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHORJukGTSE73jHv6Q1cSKrHN4hdqoHtA',
    appId: '1:18656785307:ios:95160c400984a61018273e',
    messagingSenderId: '18656785307',
    projectId: 'mynotes-e163f',
    storageBucket: 'mynotes-e163f.appspot.com',
    iosClientId: '18656785307-pab1qbtl0kqc7aao4ng0be1gc9mdd08u.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHORJukGTSE73jHv6Q1cSKrHN4hdqoHtA',
    appId: '1:18656785307:ios:95160c400984a61018273e',
    messagingSenderId: '18656785307',
    projectId: 'mynotes-e163f',
    storageBucket: 'mynotes-e163f.appspot.com',
    iosClientId: '18656785307-pab1qbtl0kqc7aao4ng0be1gc9mdd08u.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
